/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 kyanaamdu_2.0.glb 
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useThree } from "react-three-fiber";
export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/kyanaamdu_2.0.glb')
  const { actions,names } = useAnimations(animations, group)
  const { camera, mouse } = useThree();
  const modelSpeed = 0.01;

  useFrame(({ mouse, camera }) => {
    // Update position based on mouse
    // group.current.position.x = (mouse.x * window.innerWidth * modelSpeed) / 2;
    // group.current.position.y = -(mouse.y * window.innerHeight * modelSpeed) / 2;
    
    // Update position based on scroll
    
  
    // Adjust the camera position if needed based on scrolling
    // camera.position.set(0, 0, 8 - 2 * scrollPercentage);
  });
  useFrame(() => {
    group.current.rotation.x = mouse.y * 0.2;
    group.current.rotation.y = mouse.x * 0.2;
    
  });
  

 

  useEffect(() => {
    for (let i = 0; i < names.length; i++) {
      actions[names[i]].reset().fadeIn(0.5).play();
    }
  }, [actions, names]);


  return (
    <group ref={group} {...props} dispose={null} 
    >
      <group name="Scene">
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Material.004']} position={[0, -0.093, 2.487]} scale={[0.174, 0.163, 0.13]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.005']} position={[0.048, -0.188, -2.873]} scale={[0.096, 0.121, 0.096]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-0.06, 0.252, -3.094]} rotation={[Math.PI / 2, 0, 0]} scale={0.122} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0.057, 0.252, -3.094]} rotation={[Math.PI / 2, 0, 0]} scale={0.122} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[1.136, 0.278, -0.834]} scale={[0.101, 0.05, 0.05]} />
        <group name="Cube" position={[0.016, 0, -0.269]} scale={[1.181, 1, 1]}>
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} />
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.002']} />
        </group>
        <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={materials.pale} position={[3.047, 1.004, 2.187]} rotation={[0, -1.36, 0]} scale={0.147} />
        <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={materials.pale} position={[-3.035, 1.004, 2.19]} rotation={[0, -0.391, 0]} scale={0.147} />
        <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials.pale} position={[-3.035, 1.004, -2.754]} rotation={[0, -1.435, 0]} scale={0.147} />
        <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials.pale} position={[3.059, 1.004, -2.733]} rotation={[0, 0.052, 0]} scale={0.147} />
        <group name="Circle001" position={[3.079, -0.021, -2.731]}>
          <mesh name="Circle001_1" geometry={nodes.Circle001_1.geometry} material={materials['Material.001']} />
          <mesh name="Circle001_2" geometry={nodes.Circle001_2.geometry} material={materials['Material.003']} />
        </group>
        <group name="Circle" position={[1.378, 0.607, -1.984]} scale={0.421}>
          <mesh name="Circle_1" geometry={nodes.Circle_1.geometry} material={materials['Material.001']} />
          <mesh name="Circle_2" geometry={nodes.Circle_2.geometry} material={materials['Material.003']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/kyanaamdu_2.0.glb')
